### ISSUE TITLE
P1-T2 HTML and Back end for page 2

### ISSUE THREAD

**Issue by NFRNO94** [MamaRussia/1stGroup_Project#3]
## User Story
Create HTML and functionality for page 2

## Acceptance Criteria
Front End
- [x] Header
- [x] Space for the poster to appear
- [x] Place for description information
- [x] Create buttons for like and dislike

Back End
- [x] Create Ajax call to get the OMDB api working. 
- [x] Create a function to get posters to fill in the space randomly
- [x] Create function to get the information for the movies, then write to the HTML

**Comment by BriaunnaG3** [comment]
Rough Draft, but I created a card for the poster and two buttons for like and dislike
